#! /usr/bin/python

import sys
import argparse
import re

# These are slow to import, and we want --help to be fast. Call
# `ensure_imports()` to bring them in.
p9 = None
pandas = None
_done_imports = False

def main():
    args = parse_command_line(sys.argv[1:])
    plot = build_plot(args)

    if args.output is None:
        # In a not-yet-released plotnine, `(...).draw(show=True)` will work for
        # this.
        str(plot)
    else:
        # Note: generates `PlotnineWarning`s that we probably want to suppress.
        plot.save(args.output[0], **parse_kwargs(args.output[1:]))

def parse_command_line(argv):
    parser = argparse.ArgumentParser()

    dataset_group = parser.add_mutually_exclusive_group()
    dataset_group.add_argument('--dataset',
                               help='Use a built-in plotnine dataset')
    dataset_group.add_argument('--input', '-i', metavar='FILE',
                               help='Read data from FILE')

    parser.add_argument('--csv', nargs='+', metavar='ARG=VAL',
                        help='Configure csv parsing (see pandas.read_csv)')

    parser.add_argument('--output', '-o', nargs='+',
                        metavar=('FILE', 'ARG=VAL'),
                        help='Save output to FILE')

    pgrp = parser.add_argument_group('Plot elements')
    pgrp.add_argument('--geom', '-g', action='append', nargs='+',
                      metavar=('GEOM', 'ARG=VAL'),
        help='Add a geom to the plot (see plotnine.geoms)')
    pgrp.add_argument('--stat', '-s', action='append', nargs='+',
                      metavar=('STAT', 'ARG=VAL'),
        help='Add a stat to the plot (see plotnine.stats)')
    pgrp.add_argument('--ann', action='append', nargs='+',
                      metavar=('GEOM', 'ARG=VAL'),
        help='Add an annotation to the plot (see plotnine.annotate)')
    pgrp.add_argument('--scale', action='append', nargs='+',
                      metavar=('SCALE', 'ARG=VAL'),
        help='Add an annotation to the plot (see plotnine.scales)')
    pgrp.add_argument('--facet', '-f', nargs='+', metavar=('TYPE', 'ARG=VAL'),
        help='Add faceting to the plot (see plotnine.facets)')
    pgrp.add_argument('--theme', '-t', action='append', nargs='+',
                      metavar=('[NAME]', 'ARG=VAL'),
        help='''With NAME, apply a built-in theme to the plot;
                without, customize the theme (see plotnine.themes)''')
    pgrp.add_argument('--xlab',
        help='Add an x-axis label to the plot (see plotnine.xlab)')
    pgrp.add_argument('--ylab',
        help='Add a y-axis label to the plot (see plotnine.ylab)')
    pgrp.add_argument('--title',
        help='Add a title to the plot (see plotnine.ggtitle)')
    pgrp.add_argument('mapping', nargs='*',
        help='''Add an aesthetic mapping to the plot
                (see plotnine.ggplot, plotnine.aes)''')

    args = parser.parse_args(argv)

    # argparse doesn't seem to let us group things to handle this automatically.
    if args.dataset is not None and args.csv is not None:
        parser.error('argument --csv: not allowed with argument --dataset')

    if args.dataset is None and args.input is None:
        args.input = '-'

    return args

def build_plot(args):
    ensure_imports()

    def get_p9(group, name):
        name = name.replace('-', '_')
        return getattr(p9, f'{group}_{name}')

    if args.input is not None:
        file = args.input if args.input != '-' else sys.stdin
        kwargs = parse_kwargs(args.csv or [])
        kwargs.setdefault('sep', None)
        kwargs.setdefault('engine', 'python')
        data = pd.read_csv(file, **kwargs)
    else:
        import plotnine.data
        data = getattr(plotnine.data, args.dataset)

    mapping = p9.aes(**parse_kwargs(args.mapping))

    plot = p9.ggplot(data, mapping)

    for x in args.geom or []:
        plot += get_p9('geom', x[0])(**parse_layer_kwargs(x[1:]))
    for x in args.stat or []:
        plot += get_p9('stat', x[0])(**parse_layer_kwargs(x[1:]))
    for x in args.ann or []:
        plot += p9.annotate(x[0].replace('-', '_'), **parse_kwargs(x[1:]))
    for x in args.scale or []:
        plot += get_p9('scale', x[0])(**parse_scale_kwargs(x[1:]))

    for x in args.theme or []:
        # We support both named themes (`-t xkcd stroke_size=5`)...
        if '=' not in x[0]:
            plot += get_p9('theme', x[0])(**parse_kwargs(x[1:]))

        # ...and fully custom themes (`-t plot_margin=0.2`)
        else:
            plot += p9.theme(**parse_kwargs(x))

    if args.facet is not None:
        plot += get_p9('facet', args.facet[0])(**parse_kwargs(args.facet[1:]))

    more_parts = [
        p9.ggtitle(args.title) if args.title is not None else None,
        p9.xlab(args.xlab) if args.xlab is not None else None,
        p9.ylab(args.ylab) if args.ylab is not None else None,

        # Default geom, only if no geom or stat provided.
        p9.geom_point() if not args.geom and not args.stat else None
    ]

    # `plot += [...]` doesn't work, but `plot = plot + [...]` does
    plot = plot + [x for x in more_parts if x is not None]

    return plot

def parse_layer_kwargs(kwargs):
    ensure_imports()
    kwargs = parse_kwargs(kwargs)
    if 'mapping' in kwargs:
        kwargs['mapping'] = p9.aes(**kwargs['mapping'])
    return kwargs

def parse_scale_kwargs(kwargs):
    kwargs = parse_kwargs(kwargs)
    if 'min' in kwargs or 'max' in kwargs:
        kwargs['limits'] = ( kwargs.pop('min', None), kwargs.pop('max', None) )
    return kwargs

def parse_kwargs(kwargs):
    def parse_key(key):
        key = key.replace('-', '_')

        if re.match(r'^\w+$', key):
            return ('plain-key', key)
        elif match := re.match(r'^(\w+)\.(\w+)$', key):
            return ('dict-key', match.group(1), match.group(2))
        elif match := re.match(r'^\.(\w+)$', key):
            return ('implicit-dict-key', match.group(1))
        elif match := re.match(r'^(\w+)\,$', key):
            return ('list-append', match.group(1))
        elif key == ',':
            return ('implicit-list-append',)
        else:
            raise ValueError(f'bad key: "{key}"')

    def parse_val(v):
        if v.startswith(':'):
            return v[1:]
        elif (v == '-'):
            return None
        elif (v == 'y'):
            return True
        elif (v == 'n'):
            return False
        try:
            return int(v)
        except Exception as e:
            try:
                return float(v)
            except Exception as e:
                return v

    ret = {}
    implicit_base = None
    for arg in kwargs:
        (key, val) = arg.split('=', 1)
        key = parse_key(key)
        val = parse_val(val)

        def set_dict(base, sub):
            context = ret.setdefault(base, {})
            if not isinstance(context, dict):
                raise ValueError(f'Key "{base}" already contains non-dict')
            context[sub] = val

        def set_list(base):
            context = ret.setdefault(base, [])
            if not isinstance(context, list):
                raise ValueError(f'Key "{base}" already contains non-list')
            context.append(val)

        if key[0] == 'plain-key':
            ret[key[1]] = val
            implicit_base = None
        elif key[0] == 'dict-key':
            set_dict(key[1], key[2])
            implicit_base = key[1]
        elif key[0] == 'list-append':
            set_list(key[1])
            implicit_base = key[1]
        elif key[0] == 'implicit-dict-key':
            if implicit_base is None:
                raise ValueError(f'No previous base at "{arg}"')
            set_dict(implicit_base, key[1])
        elif key[0] == 'implicit-list-append':
            if implicit_base is None:
                raise ValueError(f'No previous base at "{arg}"')
            set_list(implicit_base)
        else:
            raise RuntimeError('Bad parsed key')

    return ret

def ensure_imports():
    """Make sure all the imports we need are available."""
    global p9, pd, _done_imports
    if not _done_imports:
        import plotnine
        import pandas
        p9 = plotnine
        pd = pandas

if __name__ == '__main__':
    main()
